export const Testdetail=[
    {
        sno:1,
        name:"sixface",
        test:"java",
        date:"10-10-2018/12pm",
        mark:"22/25",
        result:"pass"


    },
    {
        sno:2,
        name:"Arul",
        test:"networking",
        date:"10-10-2018/12pm",
        mark:"16/25",
        result:"pass"
    },
    {
        sno:3,
        name:"bala",
        test:"blockchain",
        date:"10-10-2018/12pm",
        mark:"14/25",
        result:"pass"
    },
    {
        sno:4,
        name:"Sriram",
        test:"javascript",
        date:"10-10-2018/12pm",
        mark:"10/25",
        result:"fail"
    },
    {
        sno:5,
        name:"Desingraja",
        test:"Angular",
        date:"10-10-2018/12pm",
        mark:"07/25",
        result:"fail"
    },
    {
        sno:1,
        name:"sixface",
        test:"java",
        date:"10-10-2018/12pm",
        mark:"22/25",
        result:"pass"


    },
    {
        sno:2,
        name:"Arul",
        test:"networking",
        date:"10-10-2018/12pm",
        mark:"16/25",
        result:"pass"
    },
    {
        sno:3,
        name:"bala",
        test:"blockchain",
        date:"10-10-2018/12pm",
        mark:"14/25",
        result:"pass"
    },
    {
        sno:4,
        name:"Sriram",
        test:"javascript",
        date:"10-10-2018/12pm",
        mark:"10/25",
        result:"fail"
    },
    {
        sno:5,
        name:"Desingraja",
        test:"Angular",
        date:"10-10-2018/12pm",
        mark:"07/25",
        result:"fail"
    },
    {
        sno:1,
        name:"sixface",
        test:"java",
        date:"10-10-2018/12pm",
        mark:"22/25",
        result:"pass"


    },
    {
        sno:2,
        name:"Arul",
        test:"networking",
        date:"10-10-2018/12pm",
        mark:"16/25",
        result:"pass"
    },
    {
        sno:3,
        name:"bala",
        test:"blockchain",
        date:"10-10-2018/12pm",
        mark:"14/25",
        result:"pass"
    },
    {
        sno:4,
        name:"Sriram",
        test:"javascript",
        date:"10-10-2018/12pm",
        mark:"10/25",
        result:"fail"
    },
    {
        sno:5,
        name:"Desingraja",
        test:"Angular",
        date:"10-10-2018/12pm",
        mark:"07/25",
        result:"fail"
    }
];
